name: Build

on:
  push:
  repository_dispatch:
    types: [run_build]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ubuntu:14.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:george-edison55/cmake-3.x
        sudo apt-get update
        sudo apt-get install -y cmake cmake-data git build-essential autoconf libtool texinfo bison flex pkg-config python
    - name: Clone
      run: |
        export REV=dirty-$(git describe --always)
        git clone https://github.com/vitasdk/buildscripts.git
        chmod +x *.sh 
    - name: Build
      run: |
        cd buildscripts
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
        mkdir build
        cd build
        cmake ..
        make -j$(nproc) tarball
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vitasdk-linux
        path: buildscripts/build/*.tar.bz2
    - uses: svenstaro/upload-release-action@v2
      if: contains(github.ref,'refs/heads/master')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: buildscripts/build/*.tar.bz2
        overwrite: true
        file_glob: true
        tag: master-linux-v2.${{github.run_number}}     
        release_name: master-linux-v2.${{github.run_number}}
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        brew update
        brew install \
          automake \
          cmake \
          libtool \
          ninja \
          python3
    - name: Clone buildscripts
      uses: actions/checkout@v3
      with:
        repository: vitasdk/buildscripts
        path: buildscripts
    - name: Set up environment
      run: |
        export REV=dirty-$(git describe --always)
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
    - name: Configure
      run: |
        cmake -S. \
              -Bbuild \
              -DCMAKE_BUILD_TYPE=Release
      working-directory: buildscripts
    - name: Build
      run: cmake --build build --target tarball
      working-directory: buildscripts
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vitasdk-macos
        path: buildscripts/build/*.tar.bz2
    - uses: svenstaro/upload-release-action@v2
      if: contains(github.ref,'refs/heads/master')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: buildscripts/build/*.tar.bz2
        overwrite: true
        file_glob: true
        tag: master-osx-v2.${{github.run_number}}     
        release_name: master-osx-v2.${{github.run_number}}
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: "msys2 {0}"
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: "ucrt64"
        install: >-
          base-devel
          git
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-ucrt-x86_64-autotools
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-python
    - name: Clone buildscripts
      uses: actions/checkout@v3
      with:
        repository: vitasdk/buildscripts
        path: buildscripts
    - name: Set up environment
      run: |
        export REV=dirty-$(git describe --always)
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
    - name: Configure
      run: |
        cmake -S. \
              -Bbuild \
              -G"MSYS Makefiles" \
              -DCMAKE_BUILD_TYPE=Release
      working-directory: buildscripts
    - name: Build
      run: cmake --build build --target tarball
      working-directory: buildscripts
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vitasdk-windows
        path: buildscripts/build/*.tar.bz2
    - uses: svenstaro/upload-release-action@v2
      if: contains(github.ref,'refs/heads/master')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: buildscripts/build/*.tar.bz2
        overwrite: true
        file_glob: true
        tag: master-win-v2.${{github.run_number}}     
        release_name: master-win-v2.${{github.run_number}}
